### ISSUE TITLE
Export publication ready plot

### ISSUE THREAD

**Issue by rocketeer1998** [acycliq/ca1#1]
Hi @acycliq. I'd like to know how to export the pciSeq HTML result to a publication-ready plot in formats like .pdf, .png, .jpeg, etc. Specifically, I want to export the cell-type map. Any ideas? Thanks a lot!

**Comment by acycliq** [comment]
There are some plugins that enable the user to export the map as a jpg etc, but havent tried them. What I usually do is to just take a screenshot, not sure if that suits you. I suspect however that the jpgs those plugins export will not be a lot better quality-wise than a screenshot.

**Comment by rocketeer1998** [comment]
But I found the cell color is too dark, which is different from the gene color. How can I make it brighter?

**Comment by acycliq** [comment]
The cell colours are semi-transparent. That helps (in my view at least) especially if you have the dapi as a background. However the colour blends with the background (either this is a dapi image or a flat black background) and looks a tone different to what you expect. I think this is what you are talking about when you say that the cell colour is too dark. 
Also the opacity changes dynamically as you zoom in/out. The cell colour gets more solid the further away you are and more transparent the more you zoom in. To remove this, comment-out 
[line 334](https://github.com/acycliq/visage/blob/0df53a5eb3b2922cc8b114231d91929a782bfef7/viewer/js/stage_polygons.js#L334) in your local `stage_polygons.js`. The cells will still look a bit transparent, but transparency will not change with the zoom level.
To remove completely the transparency, in [line 97](https://github.com/acycliq/visage/blob/0df53a5eb3b2922cc8b114231d91929a782bfef7/viewer/js/stage_polygons.js#L97)  replace `alpha = 0.8;` with  `alpha = 1.0;` (you still have to do the previous step though) 

If you still do not want to change anything from the above, then the only way I can think of is to set your cell colours a little bit brighter so when they are drawn onto the map and they blend with the background they have more or less the desirable tone.
